Feat/new landing page
micaiah-effiong/url-shortener pull request #27
Opened 2020-10-06 20:26 UTC by Emilsone

2020-10-07 09:34 UTC, micaiah-effiong requested changes

2020-10-07 09:34 UTC, micaiah-effiong commented on public/index.html
> +					<a class="mr-5 hover:text-gray-900">DASHBOARD</a>
What is the dashboard link for...?

2020-10-07 09:34 UTC, micaiah-effiong commented on public/index.html
> +					<p class="text-gray-500 text-sm text-center sm:text-left">© 2020
This tag is not necessary

2020-10-07 13:01 UTC, Emilsone reviewed
Made some changes on the footer

2020-10-08 20:33 UTC, micaiah-effiong approved these changes
Nice

2020-10-08 20:34 UTC, merged